print("Boletim Bimestral".upper())
print("Gabriella Possidério".upper())
num1 = float(input("Nota de Linguagens:"))
num2 = float(input("Nota de Matemática:"))
num3 = float(input("Nota de Ciências da Natureza:"))
num4 = float(input("Nota de Ciências Humanas:"))
print(f"A média bimestral desse estudante é: {(num1+ num2 + num3+ num4) / 4}. Obrigada!")
